repos:
  - repo: https://github.com/cpp-linter/cpp-linter-hooks
    rev: v1.1.3  # Use the tag or commit you want
    hooks:
      - id: clang-format
        args: [--style=file] # Other coding style: LLVM, GNU, Chromium, Microsoft, Mozilla, WebKit.
      - id: clang-tidy
        args: [--checks=.clang-tidy]
